// <auto-generated />
using CapProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapProject.Migrations
{
    [DbContext(typeof(LightsaberContext))]
    partial class LightsaberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapProject.Models.Component", b =>
                {
                    b.Property<int>("component_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("component_id"));

                    b.Property<string>("component_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("component_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("component_id");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            component_id = 1,
                            component_name = "Elemental Nature I",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Elemental Nature/CE3E3V2_EN_Switch_1.stl"
                        },
                        new
                        {
                            component_id = 2,
                            component_name = "Elemental Nature II",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Elemental Nature/CE3E3V2_EN_Switch_2.stl"
                        },
                        new
                        {
                            component_id = 3,
                            component_name = "Elemental Nature I",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Elemental Nature/EN_Emitter_1.stl"
                        },
                        new
                        {
                            component_id = 4,
                            component_name = "Elemental Nature II",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Elemental Nature/EN_Emitter_2.stl"
                        },
                        new
                        {
                            component_id = 5,
                            component_name = "Elemental Nature I",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Elemental Nature/EN_EndCap_1.stl"
                        },
                        new
                        {
                            component_id = 6,
                            component_name = "Elemental Nature II",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Elemental Nature/EN_EndCap_2.stl"
                        },
                        new
                        {
                            component_id = 7,
                            component_name = "Elemental Nature I",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Elemental Nature/EN_Sleeve_1.stl"
                        },
                        new
                        {
                            component_id = 8,
                            component_name = "Elemental Nature II",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Elemental Nature/EN_Sleeve_2.stl"
                        },
                        new
                        {
                            component_id = 9,
                            component_name = "Elemental Nature III",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Elemental Nature/EN_Sleeve_3.stl"
                        },
                        new
                        {
                            component_id = 10,
                            component_name = "Elemental Nature IV",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Elemental Nature/EN_Sleeve_4.stl"
                        },
                        new
                        {
                            component_id = 11,
                            component_name = "Peace and Justice I",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Peace and Justice/CE3E3V2_PJ_Switch_1.stl"
                        },
                        new
                        {
                            component_id = 12,
                            component_name = "Peace and Justice II",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Peace and Justice/CE3E3V2_PJ_Switch_2.stl"
                        },
                        new
                        {
                            component_id = 13,
                            component_name = "Peace and Justice I",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_Emitter_1.stl"
                        },
                        new
                        {
                            component_id = 14,
                            component_name = "Peace and Justice II",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_Emitter_2.stl"
                        },
                        new
                        {
                            component_id = 15,
                            component_name = "Peace and Justice I",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_EndCap_1.stl"
                        },
                        new
                        {
                            component_id = 16,
                            component_name = "Peace and Justice II",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_EndCap_2.stl"
                        },
                        new
                        {
                            component_id = 17,
                            component_name = "Peace and Justice I",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_Sleeve_1.stl"
                        },
                        new
                        {
                            component_id = 18,
                            component_name = "Peace and Justice II",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_Sleeve_2.stl"
                        },
                        new
                        {
                            component_id = 19,
                            component_name = "Peace and Justice III",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_Sleeve_3.stl"
                        },
                        new
                        {
                            component_id = 20,
                            component_name = "Peace and Justice IV",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Peace and Justice/PJ_Sleeve_4.stl"
                        },
                        new
                        {
                            component_id = 21,
                            component_name = "Power and Control I",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Power and Control/CE3E3V2_PC_Switch_1.stl"
                        },
                        new
                        {
                            component_id = 22,
                            component_name = "Power and Control II",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Power and Control/CE3E3V2_PC_Switch_1.stl"
                        },
                        new
                        {
                            component_id = 23,
                            component_name = "Power and Control I",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Power and Control/PC_Emitter_1.stl"
                        },
                        new
                        {
                            component_id = 24,
                            component_name = "Power and Control II",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Power and Control/PC_Emitter_2.stl"
                        },
                        new
                        {
                            component_id = 25,
                            component_name = "Power and Control I",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Power and Control/PC_EndCap_1.stl"
                        },
                        new
                        {
                            component_id = 26,
                            component_name = "Power and Control II",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Power and Control/PC_EndCap_2.stl"
                        },
                        new
                        {
                            component_id = 27,
                            component_name = "Power and Control I",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Power and ControlPC_Sleeve_1.stl"
                        },
                        new
                        {
                            component_id = 28,
                            component_name = "Power and Control II",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Power and Control/PC_Sleeve_2.stl"
                        },
                        new
                        {
                            component_id = 29,
                            component_name = "Power and Control III",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Power and Control/PC_Sleeve_3.stl"
                        },
                        new
                        {
                            component_id = 30,
                            component_name = "Power and Control IV",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Power and Control/PC_Sleeve_4.stl"
                        },
                        new
                        {
                            component_id = 31,
                            component_name = "Protection and Defense I",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Protection and Defense/CE3E3V2_PD_Switch_1.stl"
                        },
                        new
                        {
                            component_id = 32,
                            component_name = "Protection and Defense II",
                            component_type = "Switch",
                            filepath = "~/Lightsabers/Protection and Defense/CE3E3V2_PD_Switch_1.stl"
                        },
                        new
                        {
                            component_id = 33,
                            component_name = "Protection and Defense I",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Protection and Defense/PD_Emitter_1.stl"
                        },
                        new
                        {
                            component_id = 34,
                            component_name = "Protection and Defense II",
                            component_type = "Emitter",
                            filepath = "~/Lightsabers/Protection and Defense/PD_Emitter_2.stl"
                        },
                        new
                        {
                            component_id = 35,
                            component_name = "Protection and Defense I",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Protection and Defense/PD_EndCap_1.stl"
                        },
                        new
                        {
                            component_id = 36,
                            component_name = "Protection and Defense II",
                            component_type = "Pommel",
                            filepath = "~/Lightsabers/Protection and Defense/PD_EndCap_2.stl"
                        },
                        new
                        {
                            component_id = 37,
                            component_name = "Protection and Defense I",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Protection and Defense/PD_Sleeve_1.stl"
                        },
                        new
                        {
                            component_id = 38,
                            component_name = "Protection and Defense II",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Protection and Defense/PD_Sleeve_2.stl"
                        },
                        new
                        {
                            component_id = 39,
                            component_name = "Protection and Defense III",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Protection and Defense/PD_Sleeve_3.stl"
                        },
                        new
                        {
                            component_id = 40,
                            component_name = "Protection and Defense IV",
                            component_type = "Hilt",
                            filepath = "~/Lightsabers/Protection and Defense/PD_Sleeve_4.stl"
                        });
                });

            modelBuilder.Entity("CapProject.Models.Lightsaber", b =>
                {
                    b.Property<int>("lightsaber_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lightsaber_id"));

                    b.Property<int>("Emitter")
                        .HasColumnType("int");

                    b.Property<int>("Hilt")
                        .HasColumnType("int");

                    b.Property<int>("Pommel")
                        .HasColumnType("int");

                    b.Property<int>("Switch")
                        .HasColumnType("int");

                    b.Property<string>("blade_color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lightsaber_id");

                    b.ToTable("Lightsabers");

                    b.HasData(
                        new
                        {
                            lightsaber_id = 1,
                            Emitter = 3,
                            Hilt = 7,
                            Pommel = 5,
                            Switch = 1,
                            blade_color = "Blue",
                            name = "Example"
                        });
                });

            modelBuilder.Entity("CapProject.Models.LightsaberComponent", b =>
                {
                    b.Property<int>("lightsaber_id")
                        .HasColumnType("int");

                    b.Property<int>("component_id")
                        .HasColumnType("int");

                    b.HasKey("lightsaber_id", "component_id");

                    b.HasIndex("component_id");

                    b.ToTable("LightsaberComponent");
                });

            modelBuilder.Entity("CapProject.Models.LightsaberComponent", b =>
                {
                    b.HasOne("CapProject.Models.Component", "Component")
                        .WithMany("LightsaberComponents")
                        .HasForeignKey("component_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapProject.Models.Lightsaber", "Lightsaber")
                        .WithMany("LightsaberComponents")
                        .HasForeignKey("lightsaber_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Lightsaber");
                });

            modelBuilder.Entity("CapProject.Models.Component", b =>
                {
                    b.Navigation("LightsaberComponents");
                });

            modelBuilder.Entity("CapProject.Models.Lightsaber", b =>
                {
                    b.Navigation("LightsaberComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
